### ISSUE TITLE
'NoneType' object has no attribute 'ReadAsArray' in dev version

### ISSUE THREAD

**Issue by chrik5** [piMoll/SEILAPLAN#1]
Hallo,

Kann sein das ich die aktuelle Version nicht richtig installiert habe, da ich einfach den "dev" Zweig als ZIP-Datei geladen habe. 

Beim Klicken auf "Geländeprofil" oder andere Berechnungswerkzeuge bekomme ich folgende Fehlermeldung:

```
AttributeError: 'NoneType' object has no attribute 'ReadAsArray' 
Traceback (most recent call last):
  File "C:/Users/kanzian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SEILAPLAN-dev\gui\seilaplanPluginDialog.py", line 955, in apply
    and self.confHandler.prepareForCalculation():
  File "C:/Users/kanzian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SEILAPLAN-dev\configHandler.py", line 1095, in prepareForCalculation
    success = self.project.prepareForCalculation()
  File "C:/Users/kanzian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SEILAPLAN-dev\configHandler.py", line 453, in prepareForCalculation
    self.params.ANCHOR_LEN)
  File "C:/Users/kanzian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SEILAPLAN-dev\tool\heightSource.py", line 135, in prepareData
    z = subraster.ReadAsArray()
AttributeError: 'NoneType' object has no attribute 'ReadAsArray'
```

Falls notwendig kann ich die GIS-Daten für Tests zur Verfügung stellen.

Grüße,
Christian

**Comment by piMoll** [comment]
Hallo Christan

Vielen Dank für dein Feedback.
Du kannst durchaus den DEV branch benutzen, der ist zwar momentan noch in Entwicklung aber bereits sehr stabil (ausser jetzt gerade :)
Könntest du mir deine Seilaplan Projekteinstellungen (.txt) und das Raster zusenden? 

Grüsse
Patricia

**Comment by chrik5** [comment]
Hallo Patricia,

Danke für die rasche Rückmeldung!

Hier liegen die gewünschten Daten:
https://homepage.boku.ac.at/kanzian/dl/

Im ZIP "QGis_Lehrforst.zip" wäre auch die QGIS-Projekt-Datei und alle anderen Layer mit denen ich momentan teste.  

Koordinatensystem ist etwas speziell:

`+proj=pipeline +step +inv +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=577.326 +y=90.129 +z=463.919 +rx=5.137 +ry=1.474 +rz=5.297 +s=2.4232 +convention=position_vector +step +inv +proj=cart +ellps=bessel +step +proj=pop +v_3 +step +proj=tmerc +lat_0=0 +lon_0=16.3333333333333 +k=1 +x_0=750000 +y_0=-5000000 +ellps=bessel`

Sollte Gauss-Krüger M34 sein, aber bei den DEM XYZ das ich eingelesen habe fehlten die ersten Stellen. Vielleicht ist es ein Transformationsproblem? Von den Koordinatensystemen habe ich leider keine Ahnung.

Mittlerweile habe ich beim Testen entdeckt das QGIS das plugin Verzeichnis automatisch einliest ohne das man das Plugin extra installieren muss. Damit geht git clone und git checkout usw. ohne Umwege, was recht praktisch fürs Testen ist.

Grüsse,
Christian

**Comment by piMoll** [comment]
Ich schaue mir die Daten am Wochenende an. Deine Vermutung mit dem Koordinatensystem ist wahrscheinlich bereits eine sehr gute Spur.
Grüsse
Patricia

**Comment by piMoll** [comment]
Hallo Christian
Ich habe mir die Daten angeschaut. Leider hat sowohl dein QGIS Projekt als auch einige Geodaten ein ungültiges Koordinatensystem. Wenn Seilaplan auf dieser Basis versucht, ein Subraster für die Berechnung auszuschneiden, versagen die verwendeten Geo-Bibliotheken.

Damit das DEM korrekt dargestellt und verarbeitet werden kann, sind folgende Schritte notwendig:

1. Neues QGIS Projekt öffnen
2. Projekt-Koordinatensystem auf "MGI / Austria GK M34" (EPSG: 31259) setzen --> rechte untere Ecke "EPSG..."
3. DEM in QGIS laden
4. Rechtsklick auf DEM Layer > Export. Raster neu abspeichern und darauf achten, dass das korrekte Koordinatensystem 31259 ausgewählt ist
5. Das alte DEM entfernen und mit dem neuen Seilaplan testen

Nebst dem DEM haben auch andere Raster und Shapedateien im Projekt ein ungültiges Koordinatensystem. Ich würde die oben beschriebene Schritte bei allen betroffenen Datensätzen wiederholen und ein neues QGIS Projekt aufbauen.

Git: Wenn du den Checkout in das QGIS-Plugin Verzeichnis machst, dann kannst du einfach mit git pull den aktuellsten Stand holen und QGIS neu starten, dann ist das Plugin aktualisiert.

Grüsse
Patricia

**Comment by chrik5** [comment]
Hallo Patricia,

Danke für die Hinweise mit den Koordinaten-System. Nun funktioniert alles wunderbar!

Grüße,
Christian
